### ISSUE TITLE
Support for Next.js 9

### ISSUE THREAD

**Issue by napestershine** [steveholgado/nextjs-docker-pm2-nginx#1]
Does it support nextjs 9?

Thanks

**Comment by schrapel** [comment]
It already uses Next 9. I just created a PR with 9.1 and public folder support.

**Comment by Klypalskyi** [comment]
Does succh configuration works for Nextjs 11?

**Comment by Klypalskyi** [comment]
Does succh configuration works for Nextjs 11?
